# Generated by Django 5.0.7 on 2024-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_appointment_pets_age_appointment_pets_breed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='img',
            field=models.ImageField(default='man.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pets_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pets_breed',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='pets_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
